export const GET_PARTICIPANT_LIST = "GET_PSRTICIPANT_LIST";
export const GET_PARTICIPANT_LIST_ERROR = "GET_PARTICIPANT_LIST_ERROR";
export const GET_PARTICIPANT = "GET_PARTICIPANT";
export const GET_PARTICIPANT_ERROR = "GET_PARTICIPANT_ERROR";

export const GET_CONTEST_LIST = "GET_CONTEST_LIST";
export const GET_CONTEST_LIST_ERROR = "GET_CONTEST_LIST_ERROR";
export const GET_CONTEST = "GET_CONTEST";
export const GET_CONTEST_ERROR = "GET_CONTEST_ERROR";

